# Generated by Django 4.2.29 on 2026-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('pesapal', 'Pesapal Gateway')], max_length=20),
        ),
    ]
