# Generated by Django 4.2.29 on 2026-05-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_selected_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of the delivery address at checkout', null=True),
        ),
    ]
