# Generated by Django 4.2.29 on 2026-04-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=list, help_text="List of permissions for sub-admins, e.g. ['manage_buyers', 'manage_sellers']"),
        ),
    ]
