# Generated by Django 4.2.29 on 2026-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='landmark',
            field=models.CharField(blank=True, help_text="Popular/well-known nearby place used for delivery, e.g. 'near Kigali Heights'", max_length=255),
        ),
    ]
