# Generated by Django 4.2.30 on 2026-10-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('reset_password', 'Reset Password'), ('admin_login', 'Admin Login')], max_length=30),
        ),
    ]
