# Generated by Django 4.2.29 on 2026-05-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, help_text="Does the seller currently hold this item in stock? True = 'Ready for quick delivery'. False = 'Confirm & deliver same day'."),
        ),
    ]
