# Generated by Django 4.2.29 on 2026-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='payout_phone_number',
            field=models.CharField(blank=True, help_text='Mobile money number (e.g. 2507XXXXXXXX) escrow releases are paid out to.', max_length=20, null=True),
        ),
    ]
